- name:
  debug: 
    msg: "[WORKER] K8S_TOKEN_HOLDER - O token eh {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name:
  debug: 
    msg: "[WORKER] K8S_TOKEN_HOLDER - O hash eh {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"

- name: Removendo o cluster
  command:
    kubeadm reset --force
  register: kubeadm_reset

- name: Adicionando o worker ao cluster Kubernetes
  shell: "{{ kubeadm_join_workers }}" 
