- name: Helm add repo
  shell: helm repo add stable "{{ url_repo_helm }}"
  register: prometheus_repo_add
 
- name: Helm update
  shell: helm repo update
  register: prometheus_repo_update

- name: Instalando o Prometheus Operator
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_install


