- name: Instalando o pip
  apt:
    name:
      - python-pip
   
- name: Instalando dependecias do modulo k8s
  pip:
    name:
      - openshift
      - PyYAML

- name: Copiando o arquivo de deployment da app v1
  template:
    src: "{{ file_src_deploy_app_v1 }}"
    dest: "{{ file_dest_deploy_app_v1 }}"
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v1

- name: Copiando o arquivo de deployment da app v2
  template:
    src: "{{ file_src_deploy_app_v2 }}"
    dest: "{{ file_dest_deploy_app_v2 }}"
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v2

- name: Deploy da app v2
  k8s:
    state: present
    namespace: default
    src: "{{ file_dest_deploy_app_v2 }}"

- name: Scale down da app v1
  k8s:
    state: present
    namespace: default
    src: "{{ file_dest_deploy_app_v1 }}"

- name: Dentro de 2 minutos o app v1 sera removido. Pressione control + c
  pause:
    minutes: 2

- name: Removendo o app v1
  k8s:
    state: absent
    namespace: default
    src: "{{ file_dest_deploy_app_v1 }}"
