- name: Instalando o Docker
  shell: curl -fsSL https://get.docker.com | sh
  notify: Restart Docker

- name: Adicionando as chaves do repo apt do Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
   
- name: Adicionando o repo do Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: Instalando os pacotes kubeadm, kubelet e kubectl
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
    notify: Restart Kubelet
